export interface CorCanonica {
  canonica: string;
  sinonimos: string[];
}

export const DICIONARIO_CORES: CorCanonica[] = [
  { canonica: 'Preto', sinonimos: ['preto', 'preta'] },
  { canonica: 'Branco', sinonimos: ['branco', 'branca'] },
  { canonica: 'Vermelho', sinonimos: ['vermelho', 'vermelha', 'rubro'] },
  { canonica: 'Vermelho Escuro', sinonimos: ['vermelho escuro', 'bordo', 'bordô'] },
  { canonica: 'Vinho', sinonimos: ['vinho'] },
  { canonica: 'Azul Royal', sinonimos: ['azul royal', 'royal'] },
  { canonica: 'Azul Marinho', sinonimos: ['azul marinho', 'marinho'] },
  { canonica: 'Azul Claro', sinonimos: ['azul claro', 'celeste'] },
  { canonica: 'Azul Bebê', sinonimos: ['azul bebê', 'azul bebe'] },
  { canonica: 'Verde Bandeira', sinonimos: ['verde bandeira', 'bandeira'] },
  { canonica: 'Verde Musgo', sinonimos: ['verde musgo', 'musgo'] },
  { canonica: 'Verde Claro', sinonimos: ['verde claro'] },
  { canonica: 'Verde Limão', sinonimos: ['verde limão', 'verde limao', 'limão'] },
  { canonica: 'Amarelo', sinonimos: ['amarelo', 'amarela'] },
  { canonica: 'Amarelo Ouro', sinonimos: ['amarelo ouro', 'ouro'] },
  { canonica: 'Laranja', sinonimos: ['laranja'] },
  { canonica: 'Rosa', sinonimos: ['rosa'] },
  { canonica: 'Rosa Claro', sinonimos: ['rosa claro', 'rosê', 'rose'] },
  { canonica: 'Rosa Choque', sinonimos: ['rosa choque'] },
  { canonica: 'Pink', sinonimos: ['pink'] },
  { canonica: 'Roxo', sinonimos: ['roxo', 'roxa'] },
  { canonica: 'Lilás', sinonimos: ['lilás', 'lilas'] },
  { canonica: 'Marrom', sinonimos: ['marrom', 'castanho'] },
  { canonica: 'Marrom Café', sinonimos: ['marrom café', 'café', 'cafe'] },
  { canonica: 'Bege', sinonimos: ['bege'] },
  { canonica: 'Cru', sinonimos: ['cru', 'crua', 'natural'] },
  { canonica: 'Cinza', sinonimos: ['cinza'] },
  { canonica: 'Cinza Claro', sinonimos: ['cinza claro'] },
  { canonica: 'Cinza Escuro', sinonimos: ['cinza escuro', 'grafite'] },
  { canonica: 'Prata', sinonimos: ['prata', 'prateado', 'prateada'] },
  { canonica: 'Dourado', sinonimos: ['dourado', 'dourada', 'gold'] },
  { canonica: 'Caqui', sinonimos: ['caqui', 'cáqui'] },
  { canonica: 'Mostarda', sinonimos: ['mostarda'] },
  { canonica: 'Ferrugem', sinonimos: ['ferrugem', 'terracota'] },
  { canonica: 'Salmão', sinonimos: ['salmão', 'salmao'] },
  { canonica: 'Coral', sinonimos: ['coral'] },
  { canonica: 'Turquesa', sinonimos: ['turquesa'] },
  { canonica: 'Petróleo', sinonimos: ['petróleo', 'petroleo'] },
  { canonica: 'Rosa Neon', sinonimos: ['rosa neon', 'pink neon'] },
  { canonica: 'Verde Neon', sinonimos: ['verde neon'] },
  { canonica: 'Amarelo Neon', sinonimos: ['amarelo neon'] },
  { canonica: 'Multicolor', sinonimos: ['multicolor', 'colorido', 'arco-íris', 'arco iris'] },
];
