-- ============================================================================
-- Migration 001 — Enums, tabela lotes, bucket de imagens
-- Plano 03 (M2). Refs: ADR-0007 (4 tabelas), ADR-0009 (campos extras).
-- ============================================================================

-- Extensões necessárias
-- Nota: supabase_vault já vem instalado (v0.3.1) e não depende mais de pgsodium
-- (Supabase removeu pgsodium em 2024). Vault padrão é suficiente para tokens OAuth.
create extension if not exists moddatetime with schema extensions;

-- ----------------------------------------------------------------------------
-- Enums de domínio
-- ----------------------------------------------------------------------------

create type public.lote_status as enum (
  'importando',  -- upload + parse em curso
  'processando', -- famílias em fila/IA/concorrência
  'revisao',     -- aguardando aprovação humana
  'publicando',  -- enfileirado pro Mercado Livre
  'concluido',   -- terminado (todas as famílias publicadas ou erro definitivo)
  'erro'         -- falha na ingestão (planilha inválida etc.)
);

create type public.familia_status as enum (
  'pendente',    -- recém criada pelo ingest
  'processando', -- worker pegou (lock de idempotência)
  'pronto',      -- IA terminou, vai pra tela de revisão
  'publicando',  -- enviado pra fila de publicação
  'publicado',  -- POST/PUT /items OK
  'erro'         -- falha definitiva
);

create type public.operacao_ml as enum ('CREATE', 'UPDATE');

create type public.tipo_aviamento as enum ('linha', 'botao', 'fita', 'outro');

create type public.tipo_origem as enum ('regex', 'ia', 'manual');

create type public.estrategia_preco as enum ('proprio', 'competitivo', 'manual');

create type public.cor_origem as enum ('descricao', 'vision', 'manual');

-- ----------------------------------------------------------------------------
-- Tabela: lotes
-- ----------------------------------------------------------------------------

create table public.lotes (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  numero        bigint generated by default as identity, -- amigável pra UI ("Lote #42")
  status        public.lote_status not null default 'importando',
  planilha_path text,  -- path no bucket imagens
  imagens_paths text[] not null default '{}',
  total_familias       integer not null default 0,
  total_publicadas     integer not null default 0,
  total_erros          integer not null default 0,
  erro_mensagem        text,
  criado_em     timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index lotes_user_id_criado_em_idx on public.lotes (user_id, criado_em desc);

create trigger lotes_set_updated_at
  before update on public.lotes
  for each row execute procedure extensions.moddatetime (atualizado_em);

-- RLS
alter table public.lotes enable row level security;

create policy "lotes: select own"  on public.lotes for select using (auth.uid() = user_id);
create policy "lotes: insert own"  on public.lotes for insert with check (auth.uid() = user_id);
create policy "lotes: update own"  on public.lotes for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "lotes: delete own"  on public.lotes for delete using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- Storage bucket: imagens (privado, com policies por user_id)
-- ----------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('imagens', 'imagens', false)
on conflict (id) do nothing;

-- Path layout: {user_id}/{lote_id}/{filename}
-- A primeira pasta do path tem que bater com auth.uid() (storage.foldername(name))[1]

create policy "imagens: select own"
  on storage.objects for select
  using (bucket_id = 'imagens' and auth.uid()::text = (storage.foldername(name))[1]);

create policy "imagens: insert own"
  on storage.objects for insert
  with check (bucket_id = 'imagens' and auth.uid()::text = (storage.foldername(name))[1]);

create policy "imagens: update own"
  on storage.objects for update
  using (bucket_id = 'imagens' and auth.uid()::text = (storage.foldername(name))[1]);

create policy "imagens: delete own"
  on storage.objects for delete
  using (bucket_id = 'imagens' and auth.uid()::text = (storage.foldername(name))[1]);
